folder_path_training = ["fruits-360_dataset/fruits-360/Training/Apple Braeburn",
                "fruits-360_dataset/fruits-360/Training/Apple Golden 1",
                "fruits-360_dataset/fruits-360/Training/Apple Pink Lady",
                "fruits-360_dataset/fruits-360/Training/Apricot",
                "fruits-360_dataset/fruits-360/Training/Avocado",
                "fruits-360_dataset/fruits-360/Training/Banana",
                "fruits-360_dataset/fruits-360/Training/Beetroot",
                "fruits-360_dataset/fruits-360/Training/Blueberry",
                "fruits-360_dataset/fruits-360/Training/Cactus fruit",
                "fruits-360_dataset/fruits-360/Training/Cantaloupe 2",
                "fruits-360_dataset/fruits-360/Training/Cherry 1",
                "fruits-360_dataset/fruits-360/Training/Chestnut",
                "fruits-360_dataset/fruits-360/Training/Cocos",
                "fruits-360_dataset/fruits-360/Training/Ginger Root",
                "fruits-360_dataset/fruits-360/Training/Grape Blue",
                "fruits-360_dataset/fruits-360/Training/Hazelnut",
                "fruits-360_dataset/fruits-360/Training/Kiwi",
                "fruits-360_dataset/fruits-360/Training/Lemon",
                "fruits-360_dataset/fruits-360/Training/Lychee",
                "fruits-360_dataset/fruits-360/Training/Mango",
                "fruits-360_dataset/fruits-360/Training/Maracuja",
                "fruits-360_dataset/fruits-360/Training/Mulberry",
                "fruits-360_dataset/fruits-360/Training/Nectarine",
                "fruits-360_dataset/fruits-360/Training/Nut Forest",
                "fruits-360_dataset/fruits-360/Training/Onion Red",
                "fruits-360_dataset/fruits-360/Training/Orange",
                "fruits-360_dataset/fruits-360/Training/Papaya",
                "fruits-360_dataset/fruits-360/Training/Peach",
                "fruits-360_dataset/fruits-360/Training/Pear",
                "fruits-360_dataset/fruits-360/Training/Pepino",
                "fruits-360_dataset/fruits-360/Training/Pepper Red",
                "fruits-360_dataset/fruits-360/Training/Pineapple",
                "fruits-360_dataset/fruits-360/Training/Plum",
                "fruits-360_dataset/fruits-360/Training/Potato Red",
                "fruits-360_dataset/fruits-360/Training/Quince",
                "fruits-360_dataset/fruits-360/Training/Raspberry",
                "fruits-360_dataset/fruits-360/Training/Strawberry",
                "fruits-360_dataset/fruits-360/Training/Tamarillo",
                "fruits-360_dataset/fruits-360/Training/Tomato 1",
                "fruits-360_dataset/fruits-360/Training/Walnut"]


folder_path_test = ["fruits-360_dataset/fruits-360/Test/Apple Braeburn",
                "fruits-360_dataset/fruits-360/Test/Apple Golden 1",
                "fruits-360_dataset/fruits-360/Test/Apple Pink Lady",
                "fruits-360_dataset/fruits-360/Test/Apricot",
                "fruits-360_dataset/fruits-360/Test/Avocado",
                "fruits-360_dataset/fruits-360/Test/Banana",
                "fruits-360_dataset/fruits-360/Test/Beetroot",
                "fruits-360_dataset/fruits-360/Test/Blueberry",
                "fruits-360_dataset/fruits-360/Test/Cactus fruit",
                "fruits-360_dataset/fruits-360/Test/Cantaloupe 2",
                "fruits-360_dataset/fruits-360/Test/Cherry 1",
                "fruits-360_dataset/fruits-360/Test/Chestnut",
                "fruits-360_dataset/fruits-360/Test/Cocos",
                "fruits-360_dataset/fruits-360/Test/Ginger Root",
                "fruits-360_dataset/fruits-360/Test/Grape Blue",
                "fruits-360_dataset/fruits-360/Test/Hazelnut",
                "fruits-360_dataset/fruits-360/Test/Kiwi",
                "fruits-360_dataset/fruits-360/Test/Lemon",
                "fruits-360_dataset/fruits-360/Test/Lychee",
                "fruits-360_dataset/fruits-360/Test/Mango",
                "fruits-360_dataset/fruits-360/Test/Maracuja",
                "fruits-360_dataset/fruits-360/Test/Mulberry",
                "fruits-360_dataset/fruits-360/Test/Nectarine",
                "fruits-360_dataset/fruits-360/Test/Nut Forest",
                "fruits-360_dataset/fruits-360/Test/Onion Red",
                "fruits-360_dataset/fruits-360/Test/Orange",
                "fruits-360_dataset/fruits-360/Test/Papaya",
                "fruits-360_dataset/fruits-360/Test/Peach",
                "fruits-360_dataset/fruits-360/Test/Pear",
                "fruits-360_dataset/fruits-360/Test/Pepino",
                "fruits-360_dataset/fruits-360/Test/Pepper Red",
                "fruits-360_dataset/fruits-360/Test/Pineapple",
                "fruits-360_dataset/fruits-360/Test/Plum",
                "fruits-360_dataset/fruits-360/Test/Potato Red",
                "fruits-360_dataset/fruits-360/Test/Quince",
                "fruits-360_dataset/fruits-360/Test/Raspberry",
                "fruits-360_dataset/fruits-360/Test/Strawberry",
                "fruits-360_dataset/fruits-360/Test/Tamarillo",
                "fruits-360_dataset/fruits-360/Test/Tomato 1",
                "fruits-360_dataset/fruits-360/Test/Walnut"]

class_names = ["Apple Braeburn","Apple Golden 1","Apple Pink Lady","Apricot","Avocado","Banana","Beetroot","Blueberry","Cactus fruit","Cantaloupe 2","Cherry 1","Chestnut","Cocos","Ginger Root","Grape Blue","Hazelnut","Kiwi","Lemon","Lychee","Mango","Maracuja","Mulberry","Nectarine","Nut Forest","Onion Red","Orange","Papaya","Peach","Pear","Pepino","Pepper Red","Pineapple","Plum","Potato Red","Quince","Raspberry","Strawberry","Tamarillo","Tomato 1","Walnut"]
